<?xml version="1.0" ?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" version="1.10">
<model name="switch_with_base">
<pose>0 0 0 0 0 0</pose>
<static>false</static>

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:property name="base_width" value="1" />
<xacro:cuboid name="wall_base" a="4" b="${base_width}" c="2" weight="10000" is_kinematic="true"/>

<include>
  <name>switch</name>
  <uri>file:/$(env MODELS_DIR)/objects/switch</uri>
  <pose>0 ${base_width/2} 0.5 0 ${pi/2} ${pi/2}</pose>
</include>

<joint name="frame_to_wall_base_joint" type="fixed">
  <parent>wall_base</parent>
  <child>switch::frame</child>
</joint>

</model>
</sdf>
