<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="rover">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="sslidar.xacro" />
<xacro:include filename="wheel.xacro" />

<xacro:property name="robot_side_x" value="0.7" />
<xacro:property name="robot_side_y" value="0.7" />
<xacro:property name="robot_side_z" value="0.5" />

<xacro:property name="robot_mass" value="2" />
<xacro:property name="wheel_x_offset" value="0.4" />
<xacro:property name="wheel_y_offset" value="0.4" />
<xacro:property name="wheel_diameter" value="0.3" />

<link name="base">
    <visual name="base_visual">
        <origin  xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${robot_side_x} ${robot_side_y} ${robot_side_z}" />
        </geometry>
        <material name="blue">
            <color rgba="0 0 0.7 1.0"/>
        </material>
    </visual>

    <collision name="base_collision">
        <origin  xyz="0 0 0"/>
        <geometry>
            <box size="${robot_side_x} ${robot_side_y} ${robot_side_z}" />
        </geometry>
    </collision>
</link>

<link name="base_weight">
    <inertial>
        <mass value="${robot_mass}" />
        <inertia ixx="${robot_mass/6}" ixy="0" ixz="0" iyy="${robot_mass/6}" iyz="0" izz="${robot_mass/6}"/>
    </inertial>
    <visual name="base_visual">
        <geometry>
            <sphere radius="${robot_side_z / 2 + 0.025}"/>
            <material name="red">
                <color rgba="1.0 0 0 1.0"/>
            </material>
        </geometry>
    </visual>
</link>

<joint name="base_weight_joint" type="fixed">
    <parent link="base"/>
    <child link="base_weight"/>
</joint>

<xacro:wheel index="0" xyz="${wheel_x_offset} ${-wheel_y_offset} 0" axis="0 0 -1" diameter="${wheel_diameter}"/>
<xacro:wheel index="1" xyz="${-wheel_x_offset} ${-wheel_y_offset} 0" axis="0 0 -1" diameter="${wheel_diameter}"/>
<xacro:wheel index="2" xyz="${wheel_x_offset} ${wheel_y_offset} 0" axis="0 0 -1" diameter="${wheel_diameter}"/>
<xacro:wheel index="3" xyz="${-wheel_x_offset} ${wheel_y_offset} 0" axis="0 0 -1" diameter="${wheel_diameter}"/>

<!-- CAMERA BLOCK-->
<link name="camera"></link>
<joint name="camera_joint" type="fixed">
    <parent link="base"/>
    <child link="camera"/>
    <origin xyz="0 0 ${robot_side_z/2}"/>
</joint>
<gazebo reference="camera">
    <sensor name="camera" type="camera">
        <camera>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>320</width>
                <height>240</height>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>true</visualize>
        <topic>camera</topic>
    </sensor>
</gazebo>
<!-- END CAMERA BLOCK-->

<gazebo>
    <plugin
        filename="gz-sim-odometry-publisher-system"
        name="gz::sim::systems::OdometryPublisher">
        <odom_frame>odom</odom_frame>
        <robot_base_frame>base</robot_base_frame>
        <odom_publish_frequency>20</odom_publish_frequency>
        <odom_topic>odom</odom_topic>
        <tf_topic>tf</tf_topic>
  </plugin>
</gazebo>

<gazebo>
    <plugin
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
        <topic>joint_states</topic> <!--from <ros><remapping> -->
        <joint_name>wheel_0_joint</joint_name>
        <joint_name>wheel_1_joint</joint_name>
        <joint_name>wheel_2_joint</joint_name>
        <joint_name>wheel_3_joint</joint_name>
  </plugin>
</gazebo>

<gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
        <topic>cmd_vel</topic>

        <left_joint>wheel_0_joint</left_joint>
        <right_joint>wheel_2_joint</right_joint>
        <left_joint>wheel_1_joint</left_joint>
        <right_joint>wheel_3_joint</right_joint>

        <!-- kinematics -->
        <wheel_separation>${wheel_y_offset*2}</wheel_separation>
        <wheel_diameter>${wheel_diameter}</wheel_diameter>

        <!-- ODOMETRY -->
        <odom_publish_frequency>0</odom_publish_frequency>
    </plugin>
</gazebo>

</xacro:macro>
</include>
