<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="rover">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="$(env MODELS_DIR)/rover/sslidar.xacro" />

<xacro:property name="robot_side_len" value="0.2" />
<xacro:property name="robot_mass" value="2" />

<link name="base">
    <visual name="base_visual">
        <origin  xyz="0 0 ${-robot_side_len/2}" rpy="${pi / 2} 0 ${pi / 2}"/>
        <geometry>
            <box size="${robot_side_len} ${robot_side_len} ${robot_side_len}" />
        </geometry>
        <material name="blue">
            <color rgba="0 0 0.7 1.0"/>
        </material>
    </visual>

    <collision name="base_collision">
        <origin  xyz="0 0 0"/>
        <geometry>
            <box size="${robot_side_len} ${robot_side_len} ${robot_side_len}" />
        </geometry>
    </collision>
</link>

<link name="base_weight">
    <inertial>
        <mass value="${robot_mass}" />
        <inertia ixx="${robot_mass/6}" ixy="0" ixz="0" iyy="${robot_mass/6}" iyz="0" izz="${robot_mass/6}"/>
    </inertial>
    <visual name="base_visual">
        <geometry>
            <sphere radius="0.08"/>
            <material name="red">
                <color rgba="1.0 0 0 1.0"/>
            </material>
        </geometry>
    </visual>
</link>

<joint name="base_weight_joint" type="fixed">
    <parent link="base"/>
    <child link="base_weight"/>
</joint>

</xacro:macro>
</include>
