<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="rover">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="sslidar.xacro" />
<xacro:include filename="wheel.xacro" />

<xacro:property name="robot_side_x" value="0.898" />
<xacro:property name="robot_side_y" value="0.426" />
<xacro:property name="robot_side_z" value="0.278" />
<xacro:property name="z_offset_to_center" value="${robot_side_z / 2 - 0.043}" />

<xacro:property name="robot_mass" value="30" />
<xacro:property name="wheel_x_offset" value="0.25" />
<xacro:property name="wheel_y_offset" value="0.3005" />
<xacro:property name="wheel_radius" value="0.185" />

<link name="base">
    <visual name="base_visual">
        <geometry>
            <mesh filename="file://$(env MODELS_DIR)/rover/stl/explorer-base.stl"/>
        </geometry>
        <material name="gray">
            <color rgba="0.4 0.4 0.4 1.0"/>
        </material>
    </visual>
    <collision name="base_collision">
        <origin  xyz="0 0 ${z_offset_to_center}"/>
        <geometry>
            <box size="${robot_side_x} ${robot_side_y} ${robot_side_z}" />
        </geometry>
    </collision>
</link>

<link name="base_weight">
    <inertial>
        <mass value="${robot_mass}" />
        <inertia ixx="${robot_mass/6}" ixy="0" ixz="0" iyy="${robot_mass/6}" iyz="0" izz="${robot_mass/6}"/>
    </inertial>
    <visual name="base_visual">
        <geometry>
            <!--<sphere radius="${robot_side_z / 2 + 0.025}"/>-->
            <sphere radius="0.1"/>
        </geometry>
        <material name="blue">
            <color rgba="0 0 1.0 1.0"/>
        </material>
    </visual>
</link>

<joint name="base_weight_joint" type="fixed">
    <parent link="base"/>
    <child link="base_weight"/>
    <origin xyz="0 0 ${z_offset_to_center}" rpy="0 0 0"/>
</joint>

<link name="top_face">
    <visual name="top_face_visual">
        <geometry>
            <mesh filename="file://$(env MODELS_DIR)/rover/stl/top-face.stl"/>
        </geometry>
        <material name="red">
            <color rgba="1.0 0 0 1.0"/>
        </material>
    </visual>
</link>

<link name="top_rails">
    <visual name="top_rails_visual">
        <geometry>
            <mesh filename="file://$(env MODELS_DIR)/rover/stl/top-rails.stl"/>
        </geometry>
        <material name="black">
            <color rgba="0 0 0 1.0"/>
        </material>
    </visual>
</link>

<link name="bumper_front">
    <visual name="bumper_front_visual">
        <geometry>
            <mesh filename="file://$(env MODELS_DIR)/rover/stl/bumper.stl"/>
        </geometry>
        <material name="black">
            <color rgba="0 0 0 1.0"/>
        </material>
    </visual>
</link>

<link name="bumper_back">
    <visual name="bumper_back_visual">
        <geometry>
            <mesh filename="file://$(env MODELS_DIR)/rover/stl/bumper.stl"/>
        </geometry>
        <material name="black">
            <color rgba="0 0 0 1.0"/>
        </material>
    </visual>
</link>

<joint name="bumper_front_to_base" type="fixed">
    <parent link="base"/>
    <child link="bumper_front"/>
    <origin xyz="0.383 0.001 0.029" rpy="${-pi/2} 0 ${-pi/2}"/>
</joint>
<joint name="bumper_back_to_base" type="fixed">
    <parent link="base"/>
    <child link="bumper_back"/>
    <origin xyz="-0.383 0.001 0.031" rpy="${pi/2} 0 ${-pi/2}"/>
</joint>
<joint name="top_rails_to_base" type="fixed">
    <parent link="base"/>
    <child link="top_rails"/>
    <origin xyz="0 0 0.215" rpy="0 0 0"/>
</joint>
<joint name="top_face_to_base" type="fixed">
    <parent link="base"/>
    <child link="top_face"/>
    <origin xyz="0 0 0.213" rpy="0 0 0"/>
</joint>

<xacro:wheel index="0" xyz="${wheel_x_offset} ${-wheel_y_offset} 0" yaw="0" axis="0 0 -1" radius="${wheel_radius}"/>
<xacro:wheel index="1" xyz="${-wheel_x_offset} ${-wheel_y_offset} 0" yaw="0" axis="0 0 -1" radius="${wheel_radius}"/>
<xacro:wheel index="2" xyz="${wheel_x_offset} ${wheel_y_offset} 0" yaw="${pi}" axis="0 0 1" radius="${wheel_radius}"/>
<xacro:wheel index="3" xyz="${-wheel_x_offset} ${wheel_y_offset} 0" yaw="${pi}" axis="0 0 1" radius="${wheel_radius}"/>

<!-- CAMERA BLOCK-->
<link name="camera"></link>
<joint name="camera_joint" type="fixed">
    <parent link="base"/>
    <child link="camera"/>
    <origin xyz="0 0 ${robot_side_z/2 + z_offset_to_center + 0.05}" rpy="0 0 0"/>
</joint>
<gazebo reference="camera">
    <sensor name="camera" type="camera">
        <camera>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>320</width>
                <height>240</height>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>true</visualize>
        <topic>camera</topic>
    </sensor>
</gazebo>
<!-- END CAMERA BLOCK-->

<gazebo>
    <plugin
        filename="gz-sim-odometry-publisher-system"
        name="gz::sim::systems::OdometryPublisher">
        <odom_frame>odom</odom_frame>
        <robot_base_frame>base</robot_base_frame>
        <odom_publish_frequency>20</odom_publish_frequency>
        <odom_topic>odom</odom_topic>
        <tf_topic>tf</tf_topic>
  </plugin>
</gazebo>

<gazebo>
    <plugin
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
        <topic>joint_states</topic> <!--from <ros><remapping> -->
        <joint_name>wheel_0_joint</joint_name>
        <joint_name>wheel_1_joint</joint_name>
        <joint_name>wheel_2_joint</joint_name>
        <joint_name>wheel_3_joint</joint_name>
  </plugin>
</gazebo>

<gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
        <topic>cmd_vel</topic>

        <left_joint>wheel_0_joint</left_joint>
        <right_joint>wheel_2_joint</right_joint>
        <left_joint>wheel_1_joint</left_joint>
        <right_joint>wheel_3_joint</right_joint>

        <!-- kinematics -->
        <wheel_separation>${wheel_y_offset*2}</wheel_separation>
        <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

        <!-- ODOMETRY -->
        <odom_publish_frequency>0</odom_publish_frequency>
    </plugin>
</gazebo>

</xacro:macro>
</include>
