<?xml version="1.0" ?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" version="1.10">
<world name="plane_world">

<xacro:include filename="$(env MODELS_DIR)/common/plugins.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/simple_light.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="$(env MODELS_DIR)/objects/marker/marker.xacro" />
<xacro:include filename="$(env MODELS_DIR)/objects/01-module/module.xacro" />

<include>
    <uri>file:/$(env MODELS_DIR)/objects/field</uri>
    <pose>0 0 0 0 0 0</pose>
</include>

<model name='explorer'>
    <include>
         <uri>file:/$(env MODELS_DIR)/explorer/explorer.urdf</uri>
         <pose>10 11 0.5 0.0 0 0.0</pose>
    </include>
</model>

<include>
    <uri>file:/$(env MODELS_DIR)/objects/garage</uri>
    <pose>18.068 5.732 0.1 0 0 -2.55</pose>
</include>
<joint name="garage_to_world" type="fixed">
    <parent>world</parent>
    <child>garage::garage</child>
</joint>

<xacro:macro name="garage_door_trigger" params="name force">
    <plugin
        filename="${gazebo_systems_lib_dir}/libTriggerSystems.so"
        name="trigger_systems::DoorButton">
        <hinge_joint>garage_door_joint</hinge_joint>
        <trigger_joint>${name}_button_to_frame_joint</trigger_joint>
        <percentage_activated>50</percentage_activated>
        <opening_force>${force}</opening_force>
        <closing_force>0</closing_force>
        <is_oneshot>true</is_oneshot>
        <log_name>${name}</log_name>
        <do_log>false</do_log>
    </plugin>
</xacro:macro>

<xacro:garage_door_trigger name="outer_open" force="5000"/>
<xacro:garage_door_trigger name="outer_close" force="-5000"/>
<xacro:garage_door_trigger name="inner_open" force="5000"/>
<xacro:garage_door_trigger name="inner_close" force="-5000"/>

<xacro:macro name="world_module" params="suffix pose">
    <model name='module_${suffix}'>
        <xacro:module suffix="${suffix}"/>
        <pose>${pose}</pose>
    </model>
    <joint name="module_${suffix}_to_world" type="fixed">
        <parent>world</parent>
        <child>module_${suffix}::module_base</child>
    </joint>
    <plugin
        filename="${gazebo_systems_lib_dir}/libTriggerSystems.so"
        name="trigger_systems::DoorButton">
        <hinge_joint>${suffix}_panel_door_joint</hinge_joint>
        <trigger_joint>${suffix}_door_rotator_rotator_to_frame_joint</trigger_joint>
        <percentage_activated>50</percentage_activated>
        <opening_force>100</opening_force>
        <closing_force>-100</closing_force>
        <is_oneshot>true</is_oneshot>
        <log_name>${suffix}_panel_door</log_name>
        <do_log>true</do_log>
    </plugin>
</xacro:macro>

<!--
<xacro:world_module suffix="outter" pose="3.346 12.598 1.0 0 0 1.57"/>
<xacro:world_module suffix="inner" pose="16.066 1.065 0.5 0 0 0.93"/>
-->

<xacro:macro name="pole" params="index pose image">
    <model name='pole_${index}'>
        <xacro:marker image="${image}"/>
        <pose>${pose}</pose>
    </model>
</xacro:macro>

<xacro:property name="pole_z_offset" value="-0.175"/>
<xacro:pole index="0" pose="14.2 4 ${pole_z_offset + 0.7} 0 0 0" image="31.png"/>
<xacro:pole index="1" pose="15.7 14.6 ${pole_z_offset + 2.2} 0 0 0" image="32.png"/>
<xacro:pole index="2" pose="9 10 ${pole_z_offset + 1.15} 0 0 0" image="33.png"/>
<xacro:pole index="3" pose="7 16.5 ${pole_z_offset + 1.9} 0 0 0" image="34.png"/>
<xacro:pole index="4" pose="2.5 3.7 ${pole_z_offset + 1.65} 0 0 0" image="35.png"/>
<xacro:pole index="5" pose="1.3 9.7 ${pole_z_offset + 0.9} 0 0 0" image="36.png"/>
<xacro:pole index="6" pose="1 19 ${pole_z_offset + 1.6} 0 0 0" image="37.png"/>

</world>
</sdf>
